name: Instant README update

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch: 

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependency
        run: |
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive
          ls -ahl $GITHUB_WORKSPACE

      - name: Boilerplate for action-rs/cargo@v1
        run: |
          mkdir ../cache/
          mkdir ../cache/TFM/
          mkdir ../data/

      - name: Converting log format
        run: |
          python utils/ELOMMR.py logs/*.log
          mv logs/S*/* ../cache/TFM/

      - name: Run Elo-MMR calculator
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path ./Elo-MMR/multi-skill/Cargo.toml --release --bin rate mmr TFM 
      
      - name: Checkout result
        run: |
          cat ../data/TFM/all_players.csv

      - name: Reflect to READMD.md
        run: |
          cat README.template > README.md
          echo "# Standings" >> README.md
          echo "\`\`\`" >> README.md
          cat ../data/TFM/all_players.csv >> README.md
          echo "\`\`\`" >> README.md